import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import api from '../api'

export default function Bill(){
  const { id } = useParams()
  const [data, setData] = useState(null)

  useEffect(()=>{ if(id) fetch() }, [id])
  async function fetch(){
    const res = await api.get('/payments/' + id)
    setData(res.data)
  }

  return (
    <div className="bg-white p-6 rounded shadow max-w-2xl mx-auto">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-xl font-bold">Payment Bill</h2>
        <button onClick={()=>window.print()} className="text-sm bg-blue-600 text-white px-3 py-1 rounded">Print</button>
      </div>

      {!data && <div>Loading...</div>}
      {data && (
        <div>
          <div className="mb-4">
            <div><strong>Payment No:</strong> {data.payment.paymentNumber}</div>
            <div><strong>Date:</strong> {new Date(data.payment.paymentDate).toLocaleDateString()}</div>
            <div><strong>Received By:</strong> {data.payment.receivedBy?.username}</div>
          </div>

          <div className="mb-4 border p-3">
            <div className="font-medium">Car: {data.car?.plateNumber} — {data.car?.model}</div>
            <div>Service: {data.service?.serviceName} ({data.record?.serviceCode})</div>
            <div className="font-bold mt-2">Amount Paid: {data.payment.amountPaid} Rwf</div>
          </div>

          <div className="text-sm text-gray-600 mt-4">Generated by CRPMS</div>
        </div>
      )}
    </div>
  )
}
